version: "3.9"

services:
  rentcar_database:
    image: postgres
    container_name: rentcar_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentcar
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentcar
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local